# Generated by Django 6.1 on 2026-08-16 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Stripe', max_length=150)),
                ('company_domain', models.CharField(default='stripe.com', max_length=150)),
                ('company_url', models.URLField(default='https://stripe.com')),
                ('role_title', models.CharField(default='Senior Software Engineer', max_length=150)),
                ('target_level', models.CharField(default='L5 / Senior', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('scored', 'Scored & Evaluated')], default='pending', max_length=20)),
                ('tech_stack_detected', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Stripe', max_length=150)),
                ('role_title', models.CharField(default='Senior Software Engineer', max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Live In Progress'), ('completed', 'Interview Completed'), ('evaluated', 'Scored & Evaluated')], default='scheduled', max_length=20)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('hire_recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('question_bank_payload', models.JSONField(blank=True, null=True)),
                ('transcript_payload', models.JSONField(blank=True, null=True)),
                ('evaluation_report_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.candidateassignment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
