# Generated by Django 6.1 on 2026-09-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('Entry-Level', 'Entry-Level / Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior / L5'), ('Staff', 'Staff / L6'), ('Principal', 'Principal / Lead')], default='Senior', max_length=50)),
                ('domain_interests', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('setup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='dashboard.interviewsetup')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
