# Generated by Django 6.1 on 2026-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_interviewsetup_questionbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="round_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
