from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Float, ForeignKey, DateTime, JSON, Boolean
from sqlalchemy.orm import relationship
from app.database.session import Base

class StudentMemory(Base):
    """
    Persistent student memory layer for Host Agent context.
    Maintains clean JSON states without invented or fake data.
    """
    __tablename__ = "student_memory"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    
    short_term_context = Column(JSON, default=dict, nullable=False)
    long_term_memory = Column(JSON, default=dict, nullable=False)
    
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class HostAgentEvent(Base):
    """
    Application-level events observed by Host Agent within PlaceX.
    Lightweight, structured log of user milestones and module actions.
    """
    __tablename__ = "host_agent_events"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    event_type = Column(String(100), nullable=False, index=True)
    module = Column(String(50), nullable=True, index=True)
    payload = Column(JSON, default=dict, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class HostAgentTask(Base):
    """
    Actionable daily and practice tasks proactively generated by the Host Agent.
    Grounded in actual roadmap, quiz results, coding errors, and ATS gaps.
    """
    __tablename__ = "host_agent_tasks"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    module = Column(String(50), nullable=False) # "roadmap", "coding", "quiz", "resume", "interview"
    priority = Column(String(20), default="high", nullable=False) # "high", "medium", "low"
    status = Column(String(30), default="pending", nullable=False) # "pending", "in_progress", "completed", "dismissed"
    source = Column(String(50), default="host_agent", nullable=False)
    target_route = Column(String(100), nullable=True) # UI navigation route
    task_metadata = Column(JSON, default=dict, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)


class HostLog(Base):
    """
    Execution trace for Host Agent reasoning and tool operations.
    """
    __tablename__ = "host_logs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    intent = Column(String(100), nullable=False)
    services_executed = Column(JSON, default=list, nullable=False)
    processing_time = Column(Float, nullable=False)
    prompt_tokens = Column(Integer, default=0, nullable=False)
    completion_tokens = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class AgentConversation(Base):
    """
    Persistent conversational session for Host Agent.
    Enables modern ChatGPT-style multi-chat history with '+ New Chat'.
    """
    __tablename__ = "agent_conversations"

    id = Column(String(36), primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=False, default="New Chat")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    messages = relationship("AgentMessage", back_populates="conversation", cascade="all, delete-orphan", order_by="AgentMessage.created_at.asc()")


class AgentMessage(Base):
    """
    Individual message inside a Host Agent conversation session.
    """
    __tablename__ = "agent_messages"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    conversation_id = Column(String(36), ForeignKey("agent_conversations.id", ondelete="CASCADE"), nullable=False, index=True)
    sender = Column(String(20), nullable=False) # 'user' or 'agent'
    text = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    conversation = relationship("AgentConversation", back_populates="messages")


class Notification(Base):
    """
    Actionable student notifications generated from real PlaceX events, roadmaps, and assessments.
    """
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    type = Column(String(50), nullable=False) # 'quiz', 'roadmap', 'coding', 'resume', 'interview', 'milestone'
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    priority = Column(String(20), default="normal", nullable=False) # 'normal', 'high'
    read = Column(Boolean, default=False, nullable=False)
    action_url = Column(String(100), nullable=True) # target module e.g. 'knowledge', 'roadmap', 'coding', 'resume'
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
