# Generated by Django 6.1 on 2026-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placexuser",
            name="day_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placexuser",
            name="github_repos_flagged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placexuser",
            name="linkedin_completeness_pct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
